"""
Tool implementation for query_campaign_finance.

Wraps the V1 DatatalkParser agent pipeline to execute natural language
queries against campaign finance data and return structured QueryResult.
"""

import json
import os
import sys
from dataclasses import dataclass, field
from typing import Optional

from pydantic import BaseModel


class QueryResult(BaseModel):
    """Structured response from a campaign finance query.

    Follows the design in Design-v2.md Section 2.3.
    """

    answer_hint: str  # Brief natural language summary of the result
    data: list[dict]  # Supporting data rows
    sql_query: str  # Generated SQL (for transparency/debugging)
    confidence: str  # "high", "medium", "low"
    data_sources: list[str]  # Which datasets contributed
    data_freshness: str  # Timestamp of most recent data used
    caveats: list[str]  # Limitations, out-of-scope warnings
    suggested_followups: list[str]  # Recommended next questions


def _setup_v1_imports():
    """Add the V1 agent directory to sys.path so we can import from it.

    This is a temporary hack for the prototype. A clean refactoring of the
    V1 code into backend/datatalk/nlsql/ comes later (see Design-v2.md
    Section 6, migration step 2).
    """
    # backend/ is at backend/, agent/ is at agent/ in the repo root
    backend_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    repo_root = os.path.dirname(backend_dir)
    agent_dir = os.path.join(repo_root, "agent")
    if agent_dir not in sys.path:
        sys.path.insert(0, agent_dir)


async def execute_query(question: str) -> QueryResult:
    """Execute a campaign finance query using the V1 agent pipeline.

    This is the core function called by the MCP tool. It initializes the
    V1 DatatalkParser, runs the question through it, and maps the result
    to our QueryResult structure.

    Args:
        question: Natural language question about campaign finance.

    Returns:
        QueryResult with answer, data, SQL, and metadata.
    """
    _setup_v1_imports()

    from datatalk_runner import on_chat_start, run_single_message

    # Initialize the V1 parser with default configuration.
    # These paths point to the V1 data files. In production these would
    # come from environment variables or configuration.
    look_up_table_path = os.environ.get(
        "DATATALK_LOOKUP_TABLE",
        "/data1/knowledge_agents/datasets/fec/_lookup_table_6_small_files.csv",
    )
    domain_specific_instructions = os.environ.get(
        "DATATALK_DOMAIN_INSTRUCTIONS",
        "/data1/knowledge_agents/datasets/fec/domain_specific_instructions.csv",
    )
    database = os.environ.get("DATATALK_DATABASE", "fec")
    engine = os.environ.get("DATATALK_ENGINE", "gpt-4o")

    semantic_parser = await on_chat_start(
        look_up_table_path=look_up_table_path,
        domain_specific_instructions=domain_specific_instructions,
        database=database,
        engine=engine,
    )

    result = await run_single_message(
        message=question,
        conversation_history=[],
        semantic_parser_class=semantic_parser,
    )

    # Map V1 result to QueryResult structure
    return _map_v1_result(result, question)


def _map_v1_result(v1_result: dict, question: str) -> QueryResult:
    """Map a V1 agent result dict to our QueryResult schema.

    Fields we can populate from V1:
    - answer_hint: from agent_response
    - sql_query: from generated_sql
    - suggested_followups: from agent_response (if present)

    Fields with sensible defaults for now:
    - data: empty (V1 returns formatted markdown, not structured data)
    - confidence: "medium" (V1 doesn't compute confidence)
    - data_sources: ["FEC"] (default)
    - data_freshness: "unknown" (V1 doesn't track this)
    - caveats: generic caveat about data currency
    """
    answer_hint = v1_result.get("agent_response", "")
    sql_query = v1_result.get("generated_sql", "") or ""

    # V1 doesn't return structured data rows, just formatted text.
    # A future version will extract the actual query results.
    data: list[dict] = []

    # Default metadata that V1 doesn't provide
    confidence = "medium"
    data_sources = ["FEC"]
    data_freshness = "unknown"
    caveats = [
        "Data currency depends on the last import run.",
        "Results are generated by an AI system and should be verified.",
    ]

    # V1 sometimes includes suggested queries in the response
    suggested_followups: list[str] = []

    return QueryResult(
        answer_hint=answer_hint,
        data=data,
        sql_query=sql_query,
        confidence=confidence,
        data_sources=data_sources,
        data_freshness=data_freshness,
        caveats=caveats,
        suggested_followups=suggested_followups,
    )
